
[env:esp32c3_juan_minima_diy]
extends = esp32c3_base
board = esp32-c3-devkitm-1



build_flags =
  ${esp32c3_base.build_flags}
  -D HAS_I2C=0
  -D DISABLE_I2C=1
  -D MESHTASTIC_EXCLUDE_POWER_TELEMETRY=1
  -D MESHTASTIC_EXCLUDE_ENVIRONMENTAL_SENSOR=1
  -D PRIVATE_HW
  -D MESHTASTIC_VARIANT=esp32c3_juan_minima_diy
  -I variants/esp32c3/diy/esp32c3_juan_minima_diy
 

  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1

monitor_speed = 115200
board_level = extra





