[env:super_spo_mesh]
extends = esp32c3_base
board = esp32-c3-devkitm-1

build_flags =
  ${esp32c3_base.build_flags}
  -D MESHTASTIC_EXCLUDE_AIR_QUALITY_SENSOR=1
  -D MESHTASTIC_EXCLUDE_POWER_TELEMETRY=1
  -D MESHTASTIC_EXCLUDE_ENVIRONMENTAL_SENSOR=1
  -D PRIVATE_HW
  -D MESHTASTIC_VARIANT=super_spo_mesh
  -I variants/esp32c3/diy/super_spo_mesh
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D OLED_UA

monitor_speed = 115200
board_level = extra
