name: SUPER SPO MESH Build

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build ESP32-C3 Super SPO Mesh
        uses: meshtastic/gh-action-firmware@main
        with:
          pio_platform: esp32c3
          pio_env: super_spo_mesh
          pio_target: build

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: SUPER-SPO-MESH-firmware
          path: |
            .pio/build/super_spo_mesh/*.bin
          if-no-files-found: error
